# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.runs/synth_1/Kintex_Golden_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xcku11p-ffva1156-2-i

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.cache/wt [current_project]
set_property parent.project_path /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/src/ip/generic_regs [current_project]
update_ip_catalog
set_property ip_output_repo /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/imports/Kintex_P3_Golden_script/vitis/output/kintex_upgrade_010100.elf
set_property SCOPED_TO_REF Kintex_Golden [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/imports/Kintex_P3_Golden_script/vitis/output/kintex_upgrade_010100.elf]
set_property SCOPED_TO_CELLS microblaze_0 [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/imports/Kintex_P3_Golden_script/vitis/output/kintex_upgrade_010100.elf]
read_verilog -library xil_defaultlib /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/imports/Kintex_P3_Golden_script/src/rtl/verilog/Kintex_Golden_wrapper.v
add_files /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/Kintex_Golden.bd
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_axi_cdma_0_0/Kintex_Golden_axi_cdma_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_axi_hwicap_0_0/Kintex_Golden_axi_hwicap_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_axi_hwicap_0_0/Kintex_Golden_axi_hwicap_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_axi_hwicap_0_0/Kintex_Golden_axi_hwicap_0_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_auto_us_0/Kintex_Golden_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_auto_us_0/Kintex_Golden_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_auto_us_0/Kintex_Golden_auto_us_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_auto_ds_0/Kintex_Golden_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_auto_ds_0/Kintex_Golden_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_auto_ds_0/Kintex_Golden_auto_ds_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_auto_ds_1/Kintex_Golden_auto_ds_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_auto_ds_1/Kintex_Golden_auto_ds_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_auto_ds_1/Kintex_Golden_auto_ds_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_auto_ds_2/Kintex_Golden_auto_ds_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_auto_ds_2/Kintex_Golden_auto_ds_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_auto_ds_2/Kintex_Golden_auto_ds_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_axi_quad_spi_0_0/Kintex_Golden_axi_quad_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_axi_quad_spi_0_0/Kintex_Golden_axi_quad_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_axi_quad_spi_0_0/Kintex_Golden_axi_quad_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_axi_quad_spi_0_0/Kintex_Golden_axi_quad_spi_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_axi_uartlite_0_0/Kintex_Golden_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_axi_uartlite_0_0/Kintex_Golden_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_axi_uartlite_0_0/Kintex_Golden_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_blk_mem_gen_0_0/Kintex_Golden_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_blk_mem_gen_1_0/Kintex_Golden_blk_mem_gen_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_blk_mem_gen_2_0/Kintex_Golden_blk_mem_gen_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_mdm_1_0/Kintex_Golden_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_mdm_1_0/Kintex_Golden_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_microblaze_0_0/Kintex_Golden_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_microblaze_0_0/Kintex_Golden_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_microblaze_0_axi_intc_0/Kintex_Golden_microblaze_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_microblaze_0_axi_intc_0/Kintex_Golden_microblaze_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_microblaze_0_axi_intc_0/Kintex_Golden_microblaze_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_auto_pc_7/Kintex_Golden_auto_pc_7_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_auto_us_1/Kintex_Golden_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_auto_us_1/Kintex_Golden_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_auto_us_1/Kintex_Golden_auto_us_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_auto_ds_3/Kintex_Golden_auto_ds_3_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_auto_ds_3/Kintex_Golden_auto_ds_3_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_auto_ds_3/Kintex_Golden_auto_ds_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_auto_pc_0/Kintex_Golden_auto_pc_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_auto_ds_4/Kintex_Golden_auto_ds_4_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_auto_ds_4/Kintex_Golden_auto_ds_4_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_auto_ds_4/Kintex_Golden_auto_ds_4_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_auto_pc_1/Kintex_Golden_auto_pc_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_auto_ds_5/Kintex_Golden_auto_ds_5_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_auto_ds_5/Kintex_Golden_auto_ds_5_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_auto_ds_5/Kintex_Golden_auto_ds_5_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_auto_pc_2/Kintex_Golden_auto_pc_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_auto_ds_6/Kintex_Golden_auto_ds_6_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_auto_ds_6/Kintex_Golden_auto_ds_6_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_auto_ds_6/Kintex_Golden_auto_ds_6_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_auto_pc_3/Kintex_Golden_auto_pc_3_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_auto_ds_7/Kintex_Golden_auto_ds_7_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_auto_ds_7/Kintex_Golden_auto_ds_7_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_auto_ds_7/Kintex_Golden_auto_ds_7_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_auto_pc_4/Kintex_Golden_auto_pc_4_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_auto_ds_8/Kintex_Golden_auto_ds_8_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_auto_ds_8/Kintex_Golden_auto_ds_8_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_auto_ds_8/Kintex_Golden_auto_ds_8_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_auto_pc_5/Kintex_Golden_auto_pc_5_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_auto_ds_9/Kintex_Golden_auto_ds_9_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_auto_ds_9/Kintex_Golden_auto_ds_9_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_auto_ds_9/Kintex_Golden_auto_ds_9_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_auto_pc_6/Kintex_Golden_auto_pc_6_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_lmb_bram_0/Kintex_Golden_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_proc_sys_reset_0_0/Kintex_Golden_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_proc_sys_reset_0_0/Kintex_Golden_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_util_ds_buf_0_0/Kintex_Golden_util_ds_buf_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_util_ds_buf_0_0/Kintex_Golden_util_ds_buf_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_xdma_0_0/ip_0/ip_0/synth/Kintex_Golden_xdma_0_0_pcie4_ip_gt_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_xdma_0_0/ip_0/ip_0/synth/Kintex_Golden_xdma_0_0_pcie4_ip_gt.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_xdma_0_0/ip_0/Kintex_Golden_xdma_0_0_pcie4_ip_board.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_xdma_0_0/ip_0/synth/Kintex_Golden_xdma_0_0_pcie4_ip_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_xdma_0_0/ip_0/synth/Kintex_Golden_xdma_0_0_pcie4_ip_late.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_xdma_0_0/ip_0/source/ip_pcie4_uscale_plus_x1y0.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_xdma_0_0/ip_1/xdma_v4_1_6_blk_mem_64_reg_be_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_xdma_0_0/ip_2/xdma_v4_1_6_blk_mem_64_noreg_be_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_xdma_0_0/Kintex_Golden_xdma_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_xdma_0_0/source/Kintex_Golden_xdma_0_0_pcie4_uscaleplus_ip.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_xdma_0_0/synth/Kintex_Golden_xdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/Kintex_Golden_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/sources_1/bd/Kintex_Golden/ip/Kintex_Golden_microblaze_0_0/data/mb_bootloop_le.elf]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/constrs_1/imports/constraints/Kintex_PCIe_QSPI.xdc
set_property used_in_implementation false [get_files /home/bhashni/Desktop/Bootloader_scripting/Scripting/Kintex_P3_Golden_script/workdir/Kintex_P3_Vivado/Kintex_P3_Vivado.srcs/constrs_1/imports/constraints/Kintex_PCIe_QSPI.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top Kintex_Golden_wrapper -part xcku11p-ffva1156-2-i
OPTRACE "synth_design" END { }


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Kintex_Golden_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Kintex_Golden_wrapper_utilization_synth.rpt -pb Kintex_Golden_wrapper_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
