# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/Kintex_PCIe_QSPI.xdc

# Block Designs: bd/Kintex_Golden/Kintex_Golden.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Kintex_Golden || ORIG_REF_NAME==Kintex_Golden} -quiet] -quiet

# IP: bd/Kintex_Golden/ip/Kintex_Golden_FIRST_0x40_0/Kintex_Golden_FIRST_0x40_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Kintex_Golden_FIRST_0x40_0 || ORIG_REF_NAME==Kintex_Golden_FIRST_0x40_0} -quiet] -quiet

# IP: bd/Kintex_Golden/ip/Kintex_Golden_SECOND_0x44_0/Kintex_Golden_SECOND_0x44_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Kintex_Golden_SECOND_0x44_0 || ORIG_REF_NAME==Kintex_Golden_SECOND_0x44_0} -quiet] -quiet

# IP: bd/Kintex_Golden/ip/Kintex_Golden_THIRD_0x48_0/Kintex_Golden_THIRD_0x48_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Kintex_Golden_THIRD_0x48_0 || ORIG_REF_NAME==Kintex_Golden_THIRD_0x48_0} -quiet] -quiet

# IP: bd/Kintex_Golden/ip/Kintex_Golden_axi_bram_ctrl_0_0/Kintex_Golden_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Kintex_Golden_axi_bram_ctrl_0_0 || ORIG_REF_NAME==Kintex_Golden_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/Kintex_Golden/ip/Kintex_Golden_axi_bram_ctrl_1_0/Kintex_Golden_axi_bram_ctrl_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Kintex_Golden_axi_bram_ctrl_1_0 || ORIG_REF_NAME==Kintex_Golden_axi_bram_ctrl_1_0} -quiet] -quiet

# IP: bd/Kintex_Golden/ip/Kintex_Golden_axi_bram_ctrl_2_0/Kintex_Golden_axi_bram_ctrl_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Kintex_Golden_axi_bram_ctrl_2_0 || ORIG_REF_NAME==Kintex_Golden_axi_bram_ctrl_2_0} -quiet] -quiet

# IP: bd/Kintex_Golden/ip/Kintex_Golden_axi_cdma_0_0/Kintex_Golden_axi_cdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Kintex_Golden_axi_cdma_0_0 || ORIG_REF_NAME==Kintex_Golden_axi_cdma_0_0} -quiet] -quiet

# IP: bd/Kintex_Golden/ip/Kintex_Golden_axi_hwicap_0_0/Kintex_Golden_axi_hwicap_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Kintex_Golden_axi_hwicap_0_0 || ORIG_REF_NAME==Kintex_Golden_axi_hwicap_0_0} -quiet] -quiet

# IP: bd/Kintex_Golden/ip/Kintex_Golden_xbar_0/Kintex_Golden_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Kintex_Golden_xbar_0 || ORIG_REF_NAME==Kintex_Golden_xbar_0} -quiet] -quiet

# IP: bd/Kintex_Golden/ip/Kintex_Golden_auto_us_0/Kintex_Golden_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Kintex_Golden_auto_us_0 || ORIG_REF_NAME==Kintex_Golden_auto_us_0} -quiet] -quiet

# IP: bd/Kintex_Golden/ip/Kintex_Golden_auto_ds_0/Kintex_Golden_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Kintex_Golden_auto_ds_0 || ORIG_REF_NAME==Kintex_Golden_auto_ds_0} -quiet] -quiet

# IP: bd/Kintex_Golden/ip/Kintex_Golden_auto_ds_1/Kintex_Golden_auto_ds_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Kintex_Golden_auto_ds_1 || ORIG_REF_NAME==Kintex_Golden_auto_ds_1} -quiet] -quiet

# IP: bd/Kintex_Golden/ip/Kintex_Golden_auto_ds_2/Kintex_Golden_auto_ds_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Kintex_Golden_auto_ds_2 || ORIG_REF_NAME==Kintex_Golden_auto_ds_2} -quiet] -quiet

# IP: bd/Kintex_Golden/ip/Kintex_Golden_axi_interconnect_0_0/Kintex_Golden_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Kintex_Golden_axi_interconnect_0_0 || ORIG_REF_NAME==Kintex_Golden_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/Kintex_Golden/ip/Kintex_Golden_axi_quad_spi_0_0/Kintex_Golden_axi_quad_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Kintex_Golden_axi_quad_spi_0_0 || ORIG_REF_NAME==Kintex_Golden_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/Kintex_Golden/ip/Kintex_Golden_axi_uartlite_0_0/Kintex_Golden_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Kintex_Golden_axi_uartlite_0_0 || ORIG_REF_NAME==Kintex_Golden_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/Kintex_Golden/ip/Kintex_Golden_blk_mem_gen_0_0/Kintex_Golden_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Kintex_Golden_blk_mem_gen_0_0 || ORIG_REF_NAME==Kintex_Golden_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/Kintex_Golden/ip/Kintex_Golden_blk_mem_gen_1_0/Kintex_Golden_blk_mem_gen_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Kintex_Golden_blk_mem_gen_1_0 || ORIG_REF_NAME==Kintex_Golden_blk_mem_gen_1_0} -quiet] -quiet

# IP: bd/Kintex_Golden/ip/Kintex_Golden_blk_mem_gen_2_0/Kintex_Golden_blk_mem_gen_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Kintex_Golden_blk_mem_gen_2_0 || ORIG_REF_NAME==Kintex_Golden_blk_mem_gen_2_0} -quiet] -quiet

# IP: bd/Kintex_Golden/ip/Kintex_Golden_generic_regs32_0_0/Kintex_Golden_generic_regs32_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Kintex_Golden_generic_regs32_0_0 || ORIG_REF_NAME==Kintex_Golden_generic_regs32_0_0} -quiet] -quiet

# IP: bd/Kintex_Golden/ip/Kintex_Golden_mdm_1_0/Kintex_Golden_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Kintex_Golden_mdm_1_0 || ORIG_REF_NAME==Kintex_Golden_mdm_1_0} -quiet] -quiet

# IP: bd/Kintex_Golden/ip/Kintex_Golden_microblaze_0_0/Kintex_Golden_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Kintex_Golden_microblaze_0_0 || ORIG_REF_NAME==Kintex_Golden_microblaze_0_0} -quiet] -quiet

# IP: bd/Kintex_Golden/ip/Kintex_Golden_microblaze_0_axi_intc_0/Kintex_Golden_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Kintex_Golden_microblaze_0_axi_intc_0 || ORIG_REF_NAME==Kintex_Golden_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/Kintex_Golden/ip/Kintex_Golden_xbar_1/Kintex_Golden_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Kintex_Golden_xbar_1 || ORIG_REF_NAME==Kintex_Golden_xbar_1} -quiet] -quiet

# IP: bd/Kintex_Golden/ip/Kintex_Golden_auto_pc_7/Kintex_Golden_auto_pc_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Kintex_Golden_auto_pc_7 || ORIG_REF_NAME==Kintex_Golden_auto_pc_7} -quiet] -quiet

# IP: bd/Kintex_Golden/ip/Kintex_Golden_auto_us_1/Kintex_Golden_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Kintex_Golden_auto_us_1 || ORIG_REF_NAME==Kintex_Golden_auto_us_1} -quiet] -quiet

# IP: bd/Kintex_Golden/ip/Kintex_Golden_auto_ds_3/Kintex_Golden_auto_ds_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Kintex_Golden_auto_ds_3 || ORIG_REF_NAME==Kintex_Golden_auto_ds_3} -quiet] -quiet

# IP: bd/Kintex_Golden/ip/Kintex_Golden_auto_pc_0/Kintex_Golden_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Kintex_Golden_auto_pc_0 || ORIG_REF_NAME==Kintex_Golden_auto_pc_0} -quiet] -quiet

# IP: bd/Kintex_Golden/ip/Kintex_Golden_auto_ds_4/Kintex_Golden_auto_ds_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Kintex_Golden_auto_ds_4 || ORIG_REF_NAME==Kintex_Golden_auto_ds_4} -quiet] -quiet

# IP: bd/Kintex_Golden/ip/Kintex_Golden_auto_pc_1/Kintex_Golden_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Kintex_Golden_auto_pc_1 || ORIG_REF_NAME==Kintex_Golden_auto_pc_1} -quiet] -quiet

# IP: bd/Kintex_Golden/ip/Kintex_Golden_auto_ds_5/Kintex_Golden_auto_ds_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Kintex_Golden_auto_ds_5 || ORIG_REF_NAME==Kintex_Golden_auto_ds_5} -quiet] -quiet

# IP: bd/Kintex_Golden/ip/Kintex_Golden_auto_pc_2/Kintex_Golden_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Kintex_Golden_auto_pc_2 || ORIG_REF_NAME==Kintex_Golden_auto_pc_2} -quiet] -quiet

# IP: bd/Kintex_Golden/ip/Kintex_Golden_auto_ds_6/Kintex_Golden_auto_ds_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Kintex_Golden_auto_ds_6 || ORIG_REF_NAME==Kintex_Golden_auto_ds_6} -quiet] -quiet

# IP: bd/Kintex_Golden/ip/Kintex_Golden_auto_pc_3/Kintex_Golden_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Kintex_Golden_auto_pc_3 || ORIG_REF_NAME==Kintex_Golden_auto_pc_3} -quiet] -quiet

# IP: bd/Kintex_Golden/ip/Kintex_Golden_auto_ds_7/Kintex_Golden_auto_ds_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Kintex_Golden_auto_ds_7 || ORIG_REF_NAME==Kintex_Golden_auto_ds_7} -quiet] -quiet

# IP: bd/Kintex_Golden/ip/Kintex_Golden_auto_pc_4/Kintex_Golden_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Kintex_Golden_auto_pc_4 || ORIG_REF_NAME==Kintex_Golden_auto_pc_4} -quiet] -quiet

# IP: bd/Kintex_Golden/ip/Kintex_Golden_auto_ds_8/Kintex_Golden_auto_ds_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Kintex_Golden_auto_ds_8 || ORIG_REF_NAME==Kintex_Golden_auto_ds_8} -quiet] -quiet

# IP: bd/Kintex_Golden/ip/Kintex_Golden_auto_pc_5/Kintex_Golden_auto_pc_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Kintex_Golden_auto_pc_5 || ORIG_REF_NAME==Kintex_Golden_auto_pc_5} -quiet] -quiet

# IP: bd/Kintex_Golden/ip/Kintex_Golden_auto_ds_9/Kintex_Golden_auto_ds_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Kintex_Golden_auto_ds_9 || ORIG_REF_NAME==Kintex_Golden_auto_ds_9} -quiet] -quiet

# IP: bd/Kintex_Golden/ip/Kintex_Golden_auto_pc_6/Kintex_Golden_auto_pc_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Kintex_Golden_auto_pc_6 || ORIG_REF_NAME==Kintex_Golden_auto_pc_6} -quiet] -quiet

# IP: bd/Kintex_Golden/ip/Kintex_Golden_microblaze_0_axi_periph_0/Kintex_Golden_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Kintex_Golden_microblaze_0_axi_periph_0 || ORIG_REF_NAME==Kintex_Golden_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/Kintex_Golden/ip/Kintex_Golden_dlmb_bram_if_cntlr_0/Kintex_Golden_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Kintex_Golden_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==Kintex_Golden_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Kintex_Golden/ip/Kintex_Golden_dlmb_v10_0/Kintex_Golden_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Kintex_Golden_dlmb_v10_0 || ORIG_REF_NAME==Kintex_Golden_dlmb_v10_0} -quiet] -quiet

# IP: bd/Kintex_Golden/ip/Kintex_Golden_ilmb_bram_if_cntlr_0/Kintex_Golden_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Kintex_Golden_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==Kintex_Golden_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Kintex_Golden/ip/Kintex_Golden_ilmb_v10_0/Kintex_Golden_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Kintex_Golden_ilmb_v10_0 || ORIG_REF_NAME==Kintex_Golden_ilmb_v10_0} -quiet] -quiet

# IP: bd/Kintex_Golden/ip/Kintex_Golden_lmb_bram_0/Kintex_Golden_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Kintex_Golden_lmb_bram_0 || ORIG_REF_NAME==Kintex_Golden_lmb_bram_0} -quiet] -quiet

# IP: bd/Kintex_Golden/ip/Kintex_Golden_microblaze_0_xlconcat_0/Kintex_Golden_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Kintex_Golden_microblaze_0_xlconcat_0 || ORIG_REF_NAME==Kintex_Golden_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/Kintex_Golden/ip/Kintex_Golden_proc_sys_reset_0_0/Kintex_Golden_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Kintex_Golden_proc_sys_reset_0_0 || ORIG_REF_NAME==Kintex_Golden_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/Kintex_Golden/ip/Kintex_Golden_util_ds_buf_0_0/Kintex_Golden_util_ds_buf_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Kintex_Golden_util_ds_buf_0_0 || ORIG_REF_NAME==Kintex_Golden_util_ds_buf_0_0} -quiet] -quiet

# IP: bd/Kintex_Golden/ip/Kintex_Golden_xdma_0_0/Kintex_Golden_xdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Kintex_Golden_xdma_0_0 || ORIG_REF_NAME==Kintex_Golden_xdma_0_0} -quiet] -quiet

# IP: bd/Kintex_Golden/ip/Kintex_Golden_xdma_0_0/ip_0/Kintex_Golden_xdma_0_0_pcie4_ip.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Kintex_Golden_xdma_0_0_pcie4_ip || ORIG_REF_NAME==Kintex_Golden_xdma_0_0_pcie4_ip} -quiet] -quiet

# IP: bd/Kintex_Golden/ip/Kintex_Golden_xdma_0_0/ip_0/ip_0/Kintex_Golden_xdma_0_0_pcie4_ip_gt.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Kintex_Golden_xdma_0_0_pcie4_ip_gt || ORIG_REF_NAME==Kintex_Golden_xdma_0_0_pcie4_ip_gt} -quiet] -quiet

# IP: bd/Kintex_Golden/ip/Kintex_Golden_xdma_0_0/ip_1/xdma_v4_1_6_blk_mem_64_reg_be.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xdma_v4_1_6_blk_mem_64_reg_be || ORIG_REF_NAME==xdma_v4_1_6_blk_mem_64_reg_be} -quiet] -quiet

# IP: bd/Kintex_Golden/ip/Kintex_Golden_xdma_0_0/ip_2/xdma_v4_1_6_blk_mem_64_noreg_be.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xdma_v4_1_6_blk_mem_64_noreg_be || ORIG_REF_NAME==xdma_v4_1_6_blk_mem_64_noreg_be} -quiet] -quiet

# IP: bd/Kintex_Golden/ip/Kintex_Golden_xlconstant_1_0/Kintex_Golden_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Kintex_Golden_xlconstant_1_0 || ORIG_REF_NAME==Kintex_Golden_xlconstant_1_0} -quiet] -quiet

# IP: bd/Kintex_Golden/ip/Kintex_Golden_xlconstant_2_0/Kintex_Golden_xlconstant_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Kintex_Golden_xlconstant_2_0 || ORIG_REF_NAME==Kintex_Golden_xlconstant_2_0} -quiet] -quiet

# IP: bd/Kintex_Golden/ip/Kintex_Golden_xlconstant_3_0/Kintex_Golden_xlconstant_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Kintex_Golden_xlconstant_3_0 || ORIG_REF_NAME==Kintex_Golden_xlconstant_3_0} -quiet] -quiet

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_axi_cdma_0_0/Kintex_Golden_axi_cdma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kintex_Golden_axi_cdma_0_0 || ORIG_REF_NAME==Kintex_Golden_axi_cdma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_axi_hwicap_0_0/Kintex_Golden_axi_hwicap_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kintex_Golden_axi_hwicap_0_0 || ORIG_REF_NAME==Kintex_Golden_axi_hwicap_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_axi_hwicap_0_0/Kintex_Golden_axi_hwicap_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kintex_Golden_axi_hwicap_0_0 || ORIG_REF_NAME==Kintex_Golden_axi_hwicap_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_axi_hwicap_0_0/Kintex_Golden_axi_hwicap_0_0_ooc.xdc

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_auto_us_0/Kintex_Golden_auto_us_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kintex_Golden_auto_us_0 || ORIG_REF_NAME==Kintex_Golden_auto_us_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_auto_us_0/Kintex_Golden_auto_us_0_ooc.xdc

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_auto_ds_0/Kintex_Golden_auto_ds_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kintex_Golden_auto_ds_0 || ORIG_REF_NAME==Kintex_Golden_auto_ds_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_auto_ds_0/Kintex_Golden_auto_ds_0_ooc.xdc

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_auto_ds_1/Kintex_Golden_auto_ds_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kintex_Golden_auto_ds_1 || ORIG_REF_NAME==Kintex_Golden_auto_ds_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_auto_ds_1/Kintex_Golden_auto_ds_1_ooc.xdc

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_auto_ds_2/Kintex_Golden_auto_ds_2_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kintex_Golden_auto_ds_2 || ORIG_REF_NAME==Kintex_Golden_auto_ds_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_auto_ds_2/Kintex_Golden_auto_ds_2_ooc.xdc

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_axi_quad_spi_0_0/Kintex_Golden_axi_quad_spi_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kintex_Golden_axi_quad_spi_0_0 || ORIG_REF_NAME==Kintex_Golden_axi_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_axi_quad_spi_0_0/Kintex_Golden_axi_quad_spi_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kintex_Golden_axi_quad_spi_0_0 || ORIG_REF_NAME==Kintex_Golden_axi_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_axi_quad_spi_0_0/Kintex_Golden_axi_quad_spi_0_0_ooc.xdc

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_axi_quad_spi_0_0/Kintex_Golden_axi_quad_spi_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kintex_Golden_axi_quad_spi_0_0 || ORIG_REF_NAME==Kintex_Golden_axi_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_axi_uartlite_0_0/Kintex_Golden_axi_uartlite_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kintex_Golden_axi_uartlite_0_0 || ORIG_REF_NAME==Kintex_Golden_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_axi_uartlite_0_0/Kintex_Golden_axi_uartlite_0_0_ooc.xdc

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_axi_uartlite_0_0/Kintex_Golden_axi_uartlite_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kintex_Golden_axi_uartlite_0_0 || ORIG_REF_NAME==Kintex_Golden_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_blk_mem_gen_0_0/Kintex_Golden_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_blk_mem_gen_1_0/Kintex_Golden_blk_mem_gen_1_0_ooc.xdc

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_blk_mem_gen_2_0/Kintex_Golden_blk_mem_gen_2_0_ooc.xdc

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_mdm_1_0/Kintex_Golden_mdm_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kintex_Golden_mdm_1_0 || ORIG_REF_NAME==Kintex_Golden_mdm_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_mdm_1_0/Kintex_Golden_mdm_1_0_ooc_trace.xdc

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_microblaze_0_0/Kintex_Golden_microblaze_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kintex_Golden_microblaze_0_0 || ORIG_REF_NAME==Kintex_Golden_microblaze_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_microblaze_0_0/Kintex_Golden_microblaze_0_0_ooc_debug.xdc

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_microblaze_0_axi_intc_0/Kintex_Golden_microblaze_0_axi_intc_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kintex_Golden_microblaze_0_axi_intc_0 || ORIG_REF_NAME==Kintex_Golden_microblaze_0_axi_intc_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_microblaze_0_axi_intc_0/Kintex_Golden_microblaze_0_axi_intc_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kintex_Golden_microblaze_0_axi_intc_0 || ORIG_REF_NAME==Kintex_Golden_microblaze_0_axi_intc_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_microblaze_0_axi_intc_0/Kintex_Golden_microblaze_0_axi_intc_0_ooc.xdc

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_auto_pc_7/Kintex_Golden_auto_pc_7_ooc.xdc

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_auto_us_1/Kintex_Golden_auto_us_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kintex_Golden_auto_us_1 || ORIG_REF_NAME==Kintex_Golden_auto_us_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_auto_us_1/Kintex_Golden_auto_us_1_ooc.xdc

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_auto_ds_3/Kintex_Golden_auto_ds_3_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kintex_Golden_auto_ds_3 || ORIG_REF_NAME==Kintex_Golden_auto_ds_3} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_auto_ds_3/Kintex_Golden_auto_ds_3_ooc.xdc

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_auto_pc_0/Kintex_Golden_auto_pc_0_ooc.xdc

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_auto_ds_4/Kintex_Golden_auto_ds_4_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kintex_Golden_auto_ds_4 || ORIG_REF_NAME==Kintex_Golden_auto_ds_4} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_auto_ds_4/Kintex_Golden_auto_ds_4_ooc.xdc

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_auto_pc_1/Kintex_Golden_auto_pc_1_ooc.xdc

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_auto_ds_5/Kintex_Golden_auto_ds_5_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kintex_Golden_auto_ds_5 || ORIG_REF_NAME==Kintex_Golden_auto_ds_5} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_auto_ds_5/Kintex_Golden_auto_ds_5_ooc.xdc

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_auto_pc_2/Kintex_Golden_auto_pc_2_ooc.xdc

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_auto_ds_6/Kintex_Golden_auto_ds_6_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kintex_Golden_auto_ds_6 || ORIG_REF_NAME==Kintex_Golden_auto_ds_6} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_auto_ds_6/Kintex_Golden_auto_ds_6_ooc.xdc

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_auto_pc_3/Kintex_Golden_auto_pc_3_ooc.xdc

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_auto_ds_7/Kintex_Golden_auto_ds_7_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kintex_Golden_auto_ds_7 || ORIG_REF_NAME==Kintex_Golden_auto_ds_7} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_auto_ds_7/Kintex_Golden_auto_ds_7_ooc.xdc

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_auto_pc_4/Kintex_Golden_auto_pc_4_ooc.xdc

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_auto_ds_8/Kintex_Golden_auto_ds_8_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kintex_Golden_auto_ds_8 || ORIG_REF_NAME==Kintex_Golden_auto_ds_8} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_auto_ds_8/Kintex_Golden_auto_ds_8_ooc.xdc

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_auto_pc_5/Kintex_Golden_auto_pc_5_ooc.xdc

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_auto_ds_9/Kintex_Golden_auto_ds_9_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kintex_Golden_auto_ds_9 || ORIG_REF_NAME==Kintex_Golden_auto_ds_9} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_auto_ds_9/Kintex_Golden_auto_ds_9_ooc.xdc

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_auto_pc_6/Kintex_Golden_auto_pc_6_ooc.xdc

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_lmb_bram_0/Kintex_Golden_lmb_bram_0_ooc.xdc

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_proc_sys_reset_0_0/Kintex_Golden_proc_sys_reset_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kintex_Golden_proc_sys_reset_0_0 || ORIG_REF_NAME==Kintex_Golden_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_proc_sys_reset_0_0/Kintex_Golden_proc_sys_reset_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kintex_Golden_proc_sys_reset_0_0 || ORIG_REF_NAME==Kintex_Golden_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_util_ds_buf_0_0/Kintex_Golden_util_ds_buf_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kintex_Golden_util_ds_buf_0_0 || ORIG_REF_NAME==Kintex_Golden_util_ds_buf_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_util_ds_buf_0_0/Kintex_Golden_util_ds_buf_0_0_ooc.xdc

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_xdma_0_0/ip_0/ip_0/synth/Kintex_Golden_xdma_0_0_pcie4_ip_gt_ooc.xdc

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_xdma_0_0/ip_0/ip_0/synth/Kintex_Golden_xdma_0_0_pcie4_ip_gt.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kintex_Golden_xdma_0_0_pcie4_ip_gt || ORIG_REF_NAME==Kintex_Golden_xdma_0_0_pcie4_ip_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_xdma_0_0/ip_0/Kintex_Golden_xdma_0_0_pcie4_ip_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kintex_Golden_xdma_0_0_pcie4_ip || ORIG_REF_NAME==Kintex_Golden_xdma_0_0_pcie4_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_xdma_0_0/ip_0/synth/Kintex_Golden_xdma_0_0_pcie4_ip_ooc.xdc

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_xdma_0_0/ip_0/synth/Kintex_Golden_xdma_0_0_pcie4_ip_late.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kintex_Golden_xdma_0_0_pcie4_ip || ORIG_REF_NAME==Kintex_Golden_xdma_0_0_pcie4_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_xdma_0_0/ip_0/source/ip_pcie4_uscale_plus_x1y0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kintex_Golden_xdma_0_0_pcie4_ip || ORIG_REF_NAME==Kintex_Golden_xdma_0_0_pcie4_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_xdma_0_0/ip_1/xdma_v4_1_6_blk_mem_64_reg_be_ooc.xdc

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_xdma_0_0/ip_2/xdma_v4_1_6_blk_mem_64_noreg_be_ooc.xdc

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_xdma_0_0/Kintex_Golden_xdma_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kintex_Golden_xdma_0_0 || ORIG_REF_NAME==Kintex_Golden_xdma_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_xdma_0_0/source/Kintex_Golden_xdma_0_0_pcie4_uscaleplus_ip.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kintex_Golden_xdma_0_0 || ORIG_REF_NAME==Kintex_Golden_xdma_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/Kintex_Golden/ip/Kintex_Golden_xdma_0_0/synth/Kintex_Golden_xdma_0_0_ooc.xdc

# XDC: bd/Kintex_Golden/Kintex_Golden_ooc.xdc
