set_property SRC_FILE_INFO {cfile:/home/bhashini/Desktop/Bootloader_Scripting/Scripting/zynq_script/workdir/Calisto_P2/Calisto_P2.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_0/ip_0/ip_0/synth/design_1_xdma_0_0_pcie4_ip_gt.xdc rfile:../../../Calisto_P2.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_0/ip_0/ip_0/synth/design_1_xdma_0_0_pcie4_ip_gt.xdc id:1 order:EARLY scoped_inst:design_1_i/xdma_0/inst/pcie4_ip_i/inst/gt_top_i/diablo_gt.diablo_gt_phy_wrapper/gt_wizard.gtwizard_top_i/design_1_xdma_0_0_pcie4_ip_gt_i/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/bhashini/Desktop/Bootloader_Scripting/Scripting/zynq_script/workdir/Calisto_P2/Calisto_P2.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_0/ip_0/source/ip_pcie4_uscale_plus_x1y0.xdc rfile:../../../Calisto_P2.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_0/ip_0/source/ip_pcie4_uscale_plus_x1y0.xdc id:2 order:EARLY scoped_inst:design_1_i/xdma_0/inst/pcie4_ip_i/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/bhashini/Desktop/Bootloader_Scripting/Scripting/zynq_script/workdir/Calisto_P2/Calisto_P2.srcs/constrs_1/imports/constraints/pcie.xdc rfile:../../../Calisto_P2.srcs/constrs_1/imports/constraints/pcie.xdc id:3} [current_design]
set_property SRC_FILE_INFO {cfile:/home/bhashini/Desktop/Bootloader_Scripting/Scripting/zynq_script/workdir/Calisto_P2/Calisto_P2.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_0/ip_0/synth/design_1_xdma_0_0_pcie4_ip_late.xdc rfile:../../../Calisto_P2.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_0/ip_0/synth/design_1_xdma_0_0_pcie4_ip_late.xdc id:4 order:LATE scoped_inst:design_1_i/xdma_0/inst/pcie4_ip_i/inst} [current_design]
current_instance design_1_i/xdma_0/inst/pcie4_ip_i/inst/gt_top_i/diablo_gt.diablo_gt_phy_wrapper/gt_wizard.gtwizard_top_i/design_1_xdma_0_0_pcie4_ip_gt_i/inst
set_property src_info {type:SCOPED_XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE4_CHANNEL_X0Y11 [get_cells -hierarchical -filter {NAME =~ *gen_channel_container[2].*gen_gthe4_channel_inst[0].GTHE4_CHANNEL_PRIM_INST}]
set_property src_info {type:SCOPED_XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -user gtwizard_ultrascale -tags 1025417 -type METHODOLOGY -id TIMING-3 -description "added waiver for CPLL CAL local BUFG_GT usecase"  -scope -objects [get_pins -filter {REF_PIN_NAME=~*O} -of_objects [get_cells -hierarchical -filter {NAME =~ *gen_cpll_cal_inst[*].*bufg_gt_*xoutclkmon_inst}]]
current_instance
current_instance design_1_i/xdma_0/inst/pcie4_ip_i/inst
set_property src_info {type:SCOPED_XDC file:2 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PCIE40E4_X1Y0 [get_cells pcie_4_0_pipe_inst/pcie_4_0_e4_inst]
current_instance
set_property src_info {type:SCOPED_XDC file:2 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {design_1_i/xdma_0/inst/pcie4_ip_i/inst/gt_top_i/diablo_gt.diablo_gt_phy_wrapper/gt_wizard.gtwizard_top_i/design_1_xdma_0_0_pcie4_ip_gt_i/inst/gen_gtwizard_gthe4_top.design_1_xdma_0_0_pcie4_ip_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_channel_container[2].gen_enabled_channel.gthe4_channel_wrapper_inst/channel_inst/gthe4_channel_gen.gen_gthe4_channel_inst[0].GTHE4_CHANNEL_PRIM_INST/TXOUTCLKSEL[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {design_1_i/xdma_0/inst/pcie4_ip_i/inst/gt_top_i/diablo_gt.diablo_gt_phy_wrapper/gt_wizard.gtwizard_top_i/design_1_xdma_0_0_pcie4_ip_gt_i/inst/gen_gtwizard_gthe4_top.design_1_xdma_0_0_pcie4_ip_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_channel_container[2].gen_enabled_channel.gthe4_channel_wrapper_inst/channel_inst/gthe4_channel_gen.gen_gthe4_channel_inst[0].GTHE4_CHANNEL_PRIM_INST/TXOUTCLKSEL[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {design_1_i/xdma_0/inst/pcie4_ip_i/inst/gt_top_i/diablo_gt.diablo_gt_phy_wrapper/gt_wizard.gtwizard_top_i/design_1_xdma_0_0_pcie4_ip_gt_i/inst/gen_gtwizard_gthe4_top.design_1_xdma_0_0_pcie4_ip_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_channel_container[2].gen_enabled_channel.gthe4_channel_wrapper_inst/channel_inst/gthe4_channel_gen.gen_gthe4_channel_inst[0].GTHE4_CHANNEL_PRIM_INST/TXOUTCLKSEL[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {design_1_i/xdma_0/inst/pcie4_ip_i/inst/gt_top_i/diablo_gt.diablo_gt_phy_wrapper/gt_wizard.gtwizard_top_i/design_1_xdma_0_0_pcie4_ip_gt_i/inst/gen_gtwizard_gthe4_top.design_1_xdma_0_0_pcie4_ip_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_channel_container[2].gen_enabled_channel.gthe4_channel_wrapper_inst/channel_inst/gthe4_channel_gen.gen_gthe4_channel_inst[0].GTHE4_CHANNEL_PRIM_INST/TXRATE[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {design_1_i/xdma_0/inst/pcie4_ip_i/inst/gt_top_i/diablo_gt.diablo_gt_phy_wrapper/gt_wizard.gtwizard_top_i/design_1_xdma_0_0_pcie4_ip_gt_i/inst/gen_gtwizard_gthe4_top.design_1_xdma_0_0_pcie4_ip_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_channel_container[2].gen_enabled_channel.gthe4_channel_wrapper_inst/channel_inst/gthe4_channel_gen.gen_gthe4_channel_inst[0].GTHE4_CHANNEL_PRIM_INST/RXRATE[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {design_1_i/xdma_0/inst/pcie4_ip_i/inst/gt_top_i/diablo_gt.diablo_gt_phy_wrapper/gt_wizard.gtwizard_top_i/design_1_xdma_0_0_pcie4_ip_gt_i/inst/gen_gtwizard_gthe4_top.design_1_xdma_0_0_pcie4_ip_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_channel_container[2].gen_enabled_channel.gthe4_channel_wrapper_inst/channel_inst/gthe4_channel_gen.gen_gthe4_channel_inst[0].GTHE4_CHANNEL_PRIM_INST/TXRATE[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {design_1_i/xdma_0/inst/pcie4_ip_i/inst/gt_top_i/diablo_gt.diablo_gt_phy_wrapper/gt_wizard.gtwizard_top_i/design_1_xdma_0_0_pcie4_ip_gt_i/inst/gen_gtwizard_gthe4_top.design_1_xdma_0_0_pcie4_ip_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_channel_container[2].gen_enabled_channel.gthe4_channel_wrapper_inst/channel_inst/gthe4_channel_gen.gen_gthe4_channel_inst[0].GTHE4_CHANNEL_PRIM_INST/RXRATE[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {design_1_i/xdma_0/inst/pcie4_ip_i/inst/gt_top_i/diablo_gt.diablo_gt_phy_wrapper/gt_wizard.gtwizard_top_i/design_1_xdma_0_0_pcie4_ip_gt_i/inst/gen_gtwizard_gthe4_top.design_1_xdma_0_0_pcie4_ip_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_channel_container[2].gen_enabled_channel.gthe4_channel_wrapper_inst/channel_inst/gthe4_channel_gen.gen_gthe4_channel_inst[0].GTHE4_CHANNEL_PRIM_INST/TXRATE[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {design_1_i/xdma_0/inst/pcie4_ip_i/inst/gt_top_i/diablo_gt.diablo_gt_phy_wrapper/gt_wizard.gtwizard_top_i/design_1_xdma_0_0_pcie4_ip_gt_i/inst/gen_gtwizard_gthe4_top.design_1_xdma_0_0_pcie4_ip_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_channel_container[2].gen_enabled_channel.gthe4_channel_wrapper_inst/channel_inst/gthe4_channel_gen.gen_gthe4_channel_inst[0].GTHE4_CHANNEL_PRIM_INST/RXRATE[2]}]
current_instance design_1_i/xdma_0/inst/pcie4_ip_i/inst
set_property src_info {type:SCOPED_XDC file:2 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {gt_top_i/diablo_gt.diablo_gt_phy_wrapper/phy_clk_i/bufg_gt_pclk/DIV[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {gt_top_i/diablo_gt.diablo_gt_phy_wrapper/phy_clk_i/bufg_gt_pclk/DIV[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {gt_top_i/diablo_gt.diablo_gt_phy_wrapper/phy_clk_i/bufg_gt_pclk/DIV[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -hold  1 -end   -through [get_pins [get_pins pcie_4_0_pipe_inst/pcie_4_0_e4_inst/*AXIS*] -filter DIRECTION==IN]
set_property src_info {type:SCOPED_XDC file:2 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -hold  1 -start -through [get_pins [get_pins pcie_4_0_pipe_inst/pcie_4_0_e4_inst/*AXIS*] -filter DIRECTION==OUT]
set_property src_info {type:SCOPED_XDC file:2 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -hold  1 -end   -through [get_pins [get_pins {pcie_4_0_pipe_inst/pcie_4_0_e4_inst/CFG* pcie_4_0_pipe_inst/pcie_4_0_e4_inst/CONF* pcie_4_0_pipe_inst/pcie_4_0_e4_inst/PCIECQNPREQ* pcie_4_0_pipe_inst/pcie_4_0_e4_inst/PCIERQTAG* pcie_4_0_pipe_inst/pcie_4_0_e4_inst/PCIETFC* pcie_4_0_pipe_inst/pcie_4_0_e4_inst/USERSPARE*}] -filter DIRECTION==IN]
set_property src_info {type:SCOPED_XDC file:2 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -hold  1 -start -through [get_pins [get_pins {pcie_4_0_pipe_inst/pcie_4_0_e4_inst/CFG* pcie_4_0_pipe_inst/pcie_4_0_e4_inst/CONF* pcie_4_0_pipe_inst/pcie_4_0_e4_inst/PCIECQNPREQ* pcie_4_0_pipe_inst/pcie_4_0_e4_inst/PCIERQTAG* pcie_4_0_pipe_inst/pcie_4_0_e4_inst/PCIETFC* pcie_4_0_pipe_inst/pcie_4_0_e4_inst/USERSPARE*}] -filter DIRECTION==OUT]
current_instance
set_property src_info {type:XDC file:3 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF11      [get_ports "PCI_CLK_clk_n"] ;# Bank  227 GTH
set_property src_info {type:XDC file:3 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF12      [get_ports "PCI_CLK_clk_p"] ;# Bank  227 GTH
set_property src_info {type:XDC file:3 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL1      [get_ports "pcie_mgt_0_rxn"] ;# Bank  227 GTH
set_property src_info {type:XDC file:3 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL2      [get_ports "pcie_mgt_0_rxp"] ;# Bank  227 GTH
set_property src_info {type:XDC file:3 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK7      [get_ports "pcie_mgt_0_txn"] ;# Bank  227 GTH
set_property src_info {type:XDC file:3 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK8      [get_ports "pcie_mgt_0_txp"] ;# Bank  227 GTH
current_instance design_1_i/xdma_0/inst/pcie4_ip_i/inst
set_property src_info {type:SCOPED_XDC file:4 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_ports sys_clk]] -group [get_clocks -of_objects [get_pins -hierarchical -filter {NAME =~ *gen_channel_container[2].*gen_gthe4_channel_inst[0].GTHE4_CHANNEL_PRIM_INST/TXOUTCLK}]]
set_property src_info {type:SCOPED_XDC file:4 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins -hierarchical -filter {NAME =~ *gen_channel_container[2].*gen_gthe4_channel_inst[0].GTHE4_CHANNEL_PRIM_INST/TXOUTCLK}]] -group [get_clocks -of_objects [get_ports sys_clk]]
set_property src_info {type:SCOPED_XDC file:4 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins gt_top_i/diablo_gt.diablo_gt_phy_wrapper/phy_clk_i/bufg_gt_intclk/O]] -group [get_clocks -of_objects [get_ports sys_clk]]
set_property src_info {type:SCOPED_XDC file:4 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_ports sys_clk]] -group [get_clocks -of_objects [get_pins gt_top_i/diablo_gt.diablo_gt_phy_wrapper/phy_clk_i/bufg_gt_intclk/O]]
set_property src_info {type:SCOPED_XDC file:4 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_ports sys_clk]] -group [get_clocks -of_objects [get_pins gt_top_i/diablo_gt.diablo_gt_phy_wrapper/phy_clk_i/bufg_gt_pclk/O]]
set_property src_info {type:SCOPED_XDC file:4 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins gt_top_i/diablo_gt.diablo_gt_phy_wrapper/phy_clk_i/bufg_gt_pclk/O]] -group [get_clocks -of_objects [get_ports sys_clk]]
set_property src_info {type:SCOPED_XDC file:4 line:82 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -user pcie4_uscale_plus -tags 1015842 -type METHODOLOGY -id TIMING-3 -description "added waiver as TXOUTCLK period is intentionally overriding as DRP ports used to change the configuration/speed dynamically in runtime"  -scope -objects [get_pins -hierarchical -filter {NAME =~ *gen_channel_container[2].*gen_gthe4_channel_inst[0].GT*E4_CHANNEL_PRIM_INST/TXOUTCLK}]
set_property src_info {type:SCOPED_XDC file:4 line:85 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -user pcie4_uscale_plus -tags 1015842 -type METHODOLOGY -id TIMING-1 -description "added waiver as TXOUTCLK period is intentionally overriding as DRP ports used to change the configuration/speed dynamically in runtime"  -scope -objects [get_pins -hierarchical -filter {NAME =~ *gen_channel_container[2].*gen_gthe4_channel_inst[0].GT*E4_CHANNEL_PRIM_INST/TXOUTCLK}]
set_property src_info {type:SCOPED_XDC file:4 line:88 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -user pcie4_uscale_plus -tags 1015842 -type METHODOLOGY -id TIMING-3 -description "added waiver for int clock BUFG_GT usecase and this clock will be used for small portion of the logic before perst is deasserted/removed"  -scope -objects [get_pins -filter {REF_PIN_NAME=~*O} -of_objects [get_cells -hierarchical -filter {NAME =~ *phy_clk_i/bufg_gt_intclk}]]
